# Generated by Django 4.2.16 on 2024-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="名前"
            ),
        ),
    ]
