# Generated by Django 4.2.16 on 2024-09-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_shop_icon_image_shopphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="opening_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
