# Generated by Django 4.2.16 on 2024-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_shop_capacity_alter_shop_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
